use strict;

die "perl $0 <out1> <out2>" unless @ARGV==2;

my $r1 = shift;
my $r2 = shift;

open IN1,">$r1" ||die $!;
open IN2,">$r2" || die $!;

for(my $i=0;$i<1000000000;$i++){
	print IN1 "\@ST-E00522:403:HL5K3CCXY:5:1101:2290:$i 1:N:0:AACCCCTC+TCGATTAG
TCTCAAAAATAAATAAGTAAATAACTAGCAGCTGTAGGCTGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACAACCCCTCATCTCGTATGCCGTCTTCTGCTTGAAAAAACACGCTCCAGAGAAGGGGCAGCAGAACGACAGAGAA
+
AAAFFJJJJJJJJJJJFJJJJJJJJJJJJAJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJFJFJJJJJJJJJJJJJJJJJJA<F--------7-A)7---))--)-))------------\n";
	print IN2 "\@ST-E00522:403:HL5K3CCXY:5:1101:2290:$i 2:N:0:AACCCCTC+TCGATTAG
CCAGCCTACAGCTGCTAGTTATTTACTTATTTATTTTTGAGAAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTTCGATTAGGTGTAGATCTCGGTGGTCGCCGTATCATTAAAAAACAATGTAACCGGTTCGATTGTCAGTGAGACGG
+
AAFFFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJFJJJJJJJAJJJ-7A7-------77-))))77----7-7-7----))\n";
}

close IN1;
close IN2;



